apiVersion: v1
kind: Pod
metadata:
  name: busybox-probes-readiness-ok
spec:
  containers:
  - name: busybox
    image: busybox
    args:
    - /bin/sh
    - -c
    - echo 'Hi!'; sleep 10; echo 'Healthy!'; touch /tmp/healthy; sleep 10; rm -vrf /tmp/healthy; sleep 3600;
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 1
      periodSeconds: 5